fixtures:
  forge_modules:
    stdlib: 'puppetlabs-stdlib'
    apt: 'puppetlabs-apt'
    translate: 'puppetlabs-translate'
    powershell: 'puppetlabs-powershell'
    reboot: 'puppetlabs-reboot'
  repositories:
    yumrepo_core: 
      repo: https://github.com/puppetlabs/puppetlabs-yumrepo_core.git
      puppet_version: ">= 6.0.0"
    facts: 'git://github.com/puppetlabs/puppetlabs-facts.git'
    puppet_agent: 'git://github.com/puppetlabs/puppetlabs-puppet_agent.git'
    waffle_provision: 'git://github.com/puppetlabs/waffle_provision.git'
  symlinks:
    docker: "#{source_dir}"